### ISSUE TITLE
If I use this engine to make my game, What kind of language I can use?

### ISSUE THREAD

**Issue by hyuhyua** [K1ngst0m/Aphrodite#2]
If I use this engine to make my game, What kind of language I can use?
I hope this engine can support C# if possible

**Comment by K1ngst0m** [comment]
you can use [fna](https://github.com/FNA-XNA) or [xna](https://www.microsoft.com/en-us/download/details.aspx?id=20914) if you'd like to use c#.

**Comment by hyuhyua** [comment]
Thank you very much!
